#!/bin/bash

################################################################

# rx (previously rf, changed cause you know)
# open files, cd into directories and stuff
# not the most intuitively written bash script but it werks hehe
# made by theo

################################################################

export opener="xdg-open"
# export opener="rifle" (i use rifle, so)

fzf="fzf -e --tac --reverse --info=inline --border=sharp --color=border:white"

# excluding /{run,tmp,var,sys,proc,root,dev} from search
shopt -s expand_aliases
alias fdf="find / \( -path /var -o -path /run -o -path /tmp -o -path /sys -o -path /proc -o -path /root -o -path /dev \) -prune -o -type f 2>/dev/null"
alias fdd="find / \( -path /var -o -path /run -o -path /tmp -o -path /sys -o -path /proc -o -path /root -o -path /dev \) -prune -o -type d 2>/dev/null"

################################################################

depcheck() {
  if [[ -z $(command -v fzf) ]]; then
    printf "install fzf.\
      \nfzf is required for this script to function."\
      && exit 0; fi;}

################################################################

displayhelp() {
  printf "
  rx: open files, cd into directories and stuff
  using find and fzf.
  usage: rx [options]

  OPTIONS

  => no arguments \n\t open files via \$opener. (xdg-open is set as default)
  => -l \n\t open files but don't close fzf.
  => -d \n\t open directories in a subshell.
  => -h / --help \n\t display help text.
  => -z \n\t search for files and open the directory in which they are located.\n\n";}

################################################################

depcheck

################################################################

case $1 in
  "") fdf | $fzf --bind=enter:execute'($opener {})' --bind=enter:+close ;;
  -l) fdf | $fzf --bind=enter:execute'($opener {})' ;;
  -d) folder="$(fdd | $fzf)" && cd "$folder" && \
    echo "Press Ctrl+d to exit the subshell" && $SHELL ;;
  -h|--help) displayhelp ;;
  -z) folder="$(fdd | $fzf)" && \
      cd "$(dirname $folder)" && \
    echo "Press Ctrl+d to exit the subshell" && $SHELL ;;
esac

################################################################
