[window]
padding = { x = 5, y = 0 }
startup_mode = "Maximized"

[font.bold]
family = "Adwaita Mono"
style = "Bold"

[font.bold_italic]
family = "Adwaita Mono"
style = "Bold Italic"

[font.italic]
family = "Adwaita Mono"
style = "Italic"

[font.normal]
family = "Adwaita Mono"
style = "Regular"

[colors]
selection = { text = "CellForeground", background = "#445a77" }

[colors.primary]
background = "#1d2129"
foreground = "#d8dee9"

[colors.normal]
black = "#1d2129"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#d8dee9"

[terminal]
shell = "zellij"
